services:
  api:
    build: .
    env_file: .env
    environment:
      DD_AGENT_HOST: datadog
      DD_ENV: dev
      DD_SERVICE: suporte-avendre-api
      DD_LOGS_INJECTION: "true"
      DD_TRACE_ENABLED: "true"
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - datadog
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "suporte-avendre-api"}]'

  datadog:
    image: gcr.io/datadoghq/agent:7
    env_file: .env
    environment:
      DD_SITE: datadoghq.com
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_CONTAINER_EXCLUDE: "name:datadog"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    restart: unless-stopped
